# Creating Arrays

In [1]:
import numpy as np

arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [2]:
arr1 = np.array([[1,2,4], [-1,4,5]])
arr1

array([[ 1,  2,  4],
       [-1,  4,  5]])

In [3]:
names = np.array(['Ali', 'Ahmad'])
names

array(['Ali', 'Ahmad'], dtype='<U5')

In [4]:
print(arr.ndim)
print(arr1.ndim)

1
2


In [5]:
arr1*10

array([[ 10,  20,  40],
       [-10,  40,  50]])

In [6]:
zeros = np.zeros(5)

In [7]:
zeros

array([0., 0., 0., 0., 0.])

In [8]:
ones = np.ones(10)
ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
array1 = np.array([[1,2,3], [4,-2,5], [-3,-4,4]])

#Accessing elements inside array
print(array1[0])
print(array1[1, 1])

[1 2 3]
-2


In [10]:
print('Last element from 2nd dimension: ', array1[1, -1])

Last element from 2nd dimension:  5


# Mathemetical Operations

In [11]:
array2 = np.array([[1, 2, 3],[4, 5, 6]])
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
array2 * array2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [13]:
1/ array2

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [14]:
array2*10

array([[10, 20, 30],
       [40, 50, 60]])

# Slicing

In [15]:
#Slicing

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [16]:
arr[0,1]

2

In [17]:
arr[1,1:4] = 0
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  0,  0,  0, 10]])

In [18]:
print(arr[0:2, 1:3])

[[2 3]
 [0 0]]


# datatype

In [19]:
arr.dtype

dtype('int32')

In [20]:
print(arr.dtype)
print(array1.dtype)

int32
int32


In [21]:
str_array = np.array([1, 2, 3, 4, 5], dtype = 'S')
str_array.dtype

dtype('S1')

In [22]:
i4_array = np.array([1, 2, 3, 4, 5], dtype = 'i4')
i4_array.dtype

dtype('int32')

# datatype conversion

In [23]:
#datatype conversion

float_array = np.array([1.2, 3.3, 1.3, -3.4])
print("Old datatype: ", float_array.dtype)

int_array = float_array.astype(int)
print("New datatype: ", int_array.dtype)

Old datatype:  float64
New datatype:  int32


# Copy vs View

In [24]:
orig_array = np.array([1,2,3,4,5])
copied_arr = orig_array.copy()
print(copied_arr)

#Make changings in original array, copied array should not be afected

orig_array[-1] = 101
print(copied_arr)

[1 2 3 4 5]
[1 2 3 4 5]


In [25]:
#Repeat the same with "view", copied array SHOULD be affected now
orig_array = np.array([1,2,3,4,5])
viewed_array = orig_array.view()
print(viewed_array)

orig_array[0] = 293
print(viewed_array)

[1 2 3 4 5]
[293   2   3   4   5]


# Shape 

In [26]:
ar = np.array([[1,2,3], [2,3,4],[5,6,7]])
print(ar.shape)

(3, 3)


In [27]:
ar1 = np.array([[1,2], [2,3,4],[5,6,7,2]])
print(ar1.shape)

(3,)


In [28]:
ar2 = np.array([1,2,3], ndmin = 4)
print(ar2.shape)

(1, 1, 1, 3)


# Arrange and Reshape

In [29]:
#arange
ar = np.arange(start = 1, stop = 10, step = 2)
print(ar)
ar1 = np.arange(1, 10, 2)
print(ar1)

[1 3 5 7 9]
[1 3 5 7 9]


In [30]:
#reshape
arr = np.arange(1,13)
print(arr)

#after reshaping
print('\n',arr.reshape(4,3))

[ 1  2  3  4  5  6  7  8  9 10 11 12]

 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Mathemetical and Miscellaneous Functions

In [31]:
np.sin(0)

0.0

In [32]:
import math
inp = [0, math.pi/2, math.pi]
out = np.sin(inp)
out

array([0.0000000e+00, 1.0000000e+00, 1.2246468e-16])

In [33]:
#add

a = [1,3,5,6]
b = [-1,4,6,-8]
np.add(a,b)

array([ 0,  7, 11, -2])

In [34]:
np.cos(math.pi*2)

1.0

In [35]:
np.arctan(1)

0.7853981633974483

In [36]:
np.arccos(0.7071)

0.785407753397449

In [37]:
np.arcsin(0.5)

0.5235987755982989

In [38]:
p = [64, 8, 3]
print(np.cbrt(p))

[4.         2.         1.44224957]


In [39]:
a = [1+3j, 0]
print(np.isreal(a))

[False  True]


In [40]:
b = [1+3j, 4+5j, 7+3j]
print(np.conj(b))

[1.-3.j 4.-5.j 7.-3.j]


In [41]:
#rad to deg
rad = [0, math.pi/2, math.pi]
np.rad2deg(rad)

array([  0.,  90., 180.])

In [42]:
#deg to rad
deg = [0, 90, 180]
np.deg2rad(deg)

array([0.        , 1.57079633, 3.14159265])

In [43]:
#hypotenuse
bases = [2, 3, 5, 10]
perpendicular = [3, 2, 5, 1]

hyp = np.hypot(bases, perpendicular)
hyp

array([ 3.60555128,  3.60555128,  7.07106781, 10.04987562])

In [44]:
#round off nearest to zero
inp = [0.002, 1.2323, 4.443]
print(np.rint(inp))

[0. 1. 4.]


In [45]:
#Reciprocal
a = 10.0
print(np.reciprocal(a))

0.1


In [46]:
x = np.array([[2, 23, -4],[8, 7,2]], dtype=float)
y = np.array([[8, 3],[6,-7],[7,1]], dtype=float)
x, y

(array([[ 2., 23., -4.],
        [ 8.,  7.,  2.]]),
 array([[ 8.,  3.],
        [ 6., -7.],
        [ 7.,  1.]]))

In [47]:
print(np.dot(x,y))

[[ 126. -159.]
 [ 120.  -23.]]


# Repeat

In [48]:
ar1 = [1,2,3]
repetitions = 3
np.repeat(ar1, repetitions)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

# Random

In [49]:
arr = np.random.randn(5)
arr

array([-0.33919681, -0.75607819, -0.54355368, -1.20114341,  0.6057405 ])

In [50]:
arr = np.random.randint(5)
arr

3

In [51]:
arr = np.random.rand()
arr

0.45565784226085415

# Sort

In [52]:
ar = np.random.randn(10).reshape(5,2)
print(ar)

#after sorting
print('\n\n',ar.sort())

[[-0.01393672  1.48695854]
 [ 0.850621    0.25866955]
 [ 2.04090596  0.12724721]
 [-1.22275284 -0.19980303]
 [ 0.22608086  0.14239039]]


 None
